version: '3.6'

services:
  crawler-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "crawler-app"
    ports:
      - "8000:8000"
    command: python3 crawler/manage.py runserver 0.0.0.0:8000
    restart: always

